function fig = study_CleanArtifacts(study, filenames)

if isempty(study)
wwu_msgdlg('You must call this function using a valid study name', 'study_CleanArtifacts:NoStudy', 'Ok', 'isError',true);
return
end
if isempty(filenames)
wwu_msgdlg('You must provide the names of files to clean', 'study_CleanArtifacts:NoFiles', 'Ok', 'isError',true);
return
end
h = createGUI(study, filenames);
fig = h.figure;

%**************************************************************************
function callback_cleanData(~,~,h, study, dirtyfiles)
%get options
%get the options that have no or only internal defaults
if h.check_filter.Value
Highpass = [.25, .75];
else
Highpass = 'off';
end
RemoveWhenBad = h.check_remove;
if h.check_flatline.Value 
FlatLineCriterion = 5;
else
FlatLineCriterion = 'off';
end
VisualChanges = h.check_visChanges.Value;

%get parameters supplied by the user
LineNoiseCriterion = getUserParams(h.check_lineCriteria);
ChannelCriterion = getUserParams(h.check_chanCriteria);
BurstCriterion = getUserParams(h.check_ASRCriteria);
WindowCriterion = getUserParams(h.check_remBurstCriteria);

parameters.Operation = {'Operation', 'Auto remove channels and clean data'};
parameters.date = {'Date and time', datetime("now");};

stime = datetime;
pb = uiprogressdlg(h.figure,'Message', 'Auto detecting bad channels using clean_artifacts', 'Value',0,'Title','Detect bad channels');
maxpbVal= length(dirtyfiles) * 4;
curpbVal = 0;
nFiles = length(dirtyfiles);
reportData = cell(length(dirtyfiles), 3);
%allChanLabels = {study.chanlocs.labels};

for ii = 1:nFiles
curpbVal = curpbVal + 1;
pb.Message = 'building output filename...';
pb.Value = curpbVal/maxpbVal;

[path, file, ext] = fileparts(dirtyfiles{ii});
outfilename = fullfile(path, [file, '_clean', ext]);

curpbVal = curpbVal + 1;
pb.Message = 'loading subject data...';
pb.Value = curpbVal/maxpbVal;

EEG = eeg_LoadEEGFile(dirtyfiles{ii});
fprintf('working on %i. %s\n', ii, dirtyfiles{ii});

curpbVal = curpbVal + 1;
pb.Message = 'Cleaning data...';
pb.Value = curpbVal/maxpbVal;

clean = clean_artifacts(EEG, 'WindowCriterion', WindowCriterion, ...
'BurstCriterion', BurstCriterion, 'ChannelCriterion', ChannelCriterion, ...
'LineNoiseCriterion', LineNoiseCriterion, 'Highpass', Highpass,...
'FlatLineCriterion', FlatLineCriterion);
if VisualChanges
vis_artifacts(clean, EEG);
end
EEG = clean;
if ~isfield(EEG, 'chaninfo') || ~isfield(EEG.chaninfo, 'removedchans') || isempty(EEG.chaninfo.removedchans)
fprintf('No bad channels found for subject #%i\n', ii)
reportData{ii,1} = 0;
reportData{ii,2} = 'none';   
else
removedChanLabels = {EEG.chaninfo.removedchans.labels};
removeChanString = join(removedChanLabels);
reportData{ii,1} = length(removedChanLabels);
reportData{ii,2} = removeChanString{1};
end
curpbVal = curpbVal + 1;
pb.Message = 'saving data...';
pb.Value = curpbVal/maxpbVal;
eeg_SaveEEGFile(EEG, outfilename);
end
parameters.duration = {'Duration (seconds)', datetime-stime};

eeg_UpdateProcessLog(study,'SheetName', 'auto bad chans', ...
'ColumnNames',{'# marked', 'Channels marked', 'Ouput File'},...
'RowNames',dirtyfiles, 'Values', reportData, 'Parameters',parameters)
%study_AddHistory(study, 'start', stime, 'finish', datetime, 'event', 'Auto Removed bad channels', 'paramstring', dirtyfiles);

close(h.figure);
%**************************************************************************
function p = getUserParams(checkBox)
if ~checkBox.Value
p = 'off';
else
p = checkBox.UserData.Value;
end
%**************************************************************************
function callback_toggleState(hObject, ~, h)
hObject.UserData.Enable = hObject.Value;
%**************************************************************************
function callback_close(~, ~)
closereq();
%**************************************************************************
function handles = createGUI(study, files)

scheme = eeg_LoadScheme;
Wdth = 550; Hght = 400;
bwidth = 80;

handles.figure = uifigure(...
'Color', scheme.Window.BackgroundColor.Value, ...
'Name', 'Data Cleaning',...
'NumberTitle', 'off',...
'Position', [(scheme.ScreenWidth-Wdth)/2,(scheme.ScreenHeight-Hght)/2,Wdth,Hght],...
'Resize', 'off',...
'menubar', 'none',...
'WindowStyle', 'modal');
handles.button_clean = uibutton(...
'Parent', handles.figure,...
'Text', 'Clean',...
'Position', [Wdth-bwidth-10, 5, bwidth, scheme.Button.Height.Value],...
'BackgroundColor', scheme.Button.BackgroundColor.Value,...
'FontColor', scheme.Button.FontColor.Value,...
'FontName', scheme.Button.Font.Value,...
'FontSize', scheme.Button.FontSize.Value);
handles.button_cancel = uibutton(...
'Parent', handles.figure,...
'Text', 'Cancel',...
'Position', [Wdth-(bwidth*2)-20, 5, bwidth, scheme.Button.Height.Value],...
'BackgroundColor', scheme.Button.BackgroundColor.Value,...
'FontColor', scheme.Button.FontColor.Value,...
'FontName', scheme.Button.Font.Value,...
'FontSize', scheme.Button.FontSize.Value,...
'ButtonPushedFcn', {@callback_close});
pheights = [60, 150, 100];
cDist = 30;
handles.panel(1) = uipanel('Parent', handles.figure',...
'Position', [10, 320, 480, 60],...
'Title', 'Filter',...
'BackgroundColor', scheme.Panel.BackgroundColor.Value,...
'FontName', scheme.Panel.Font.Value,...
'ForegroundColor', scheme.Panel.FontColor.Value,...
'FontSize', scheme.Panel.FontSize.Value);
handles.panel(2) = uipanel('Parent', handles.figure',...
'Position', [10, 320-pheights(2)-10, 480, pheights(2)],...
'Title', 'Bad Channel Removal/Marking',...
'BackgroundColor', scheme.Panel.BackgroundColor.Value,...
'FontName', scheme.Panel.Font.Value,...
'ForegroundColor', scheme.Panel.FontColor.Value,...
'FontSize', scheme.Panel.FontSize.Value);
handles.panel(3) = uipanel('Parent', handles.figure',...
'Position', [10, 320-pheights(2)-pheights(3)-20, 480, pheights(3)],...
'Title', 'ASR clearning and Bad Interval Removal',...
'BackgroundColor', scheme.Panel.BackgroundColor.Value,...
'FontName', scheme.Panel.Font.Value,...
'ForegroundColor', scheme.Panel.FontColor.Value,...
'FontSize', scheme.Panel.FontSize.Value);
handles.check_filter = uicheckbox('Parent', handles.panel(1),...
'Position', [10, 10, 200, 20],...
'Text', 'Apply highpass filter', ...
'Value', false,...
'FontName', scheme.Checkbox.Font.Value,...
'FontColor',scheme.Checkbox.FontColor.Value, ...
'FontSize', scheme.Checkbox.FontSize.Value);
cBottom = pheights(2) - 50;
handles.check_remove = uicheckbox('Parent', handles.panel(2),...
'Position', [10, cBottom, 400, 20],...
'Text', 'Remove bad channels (Mark as bad if unchecked)', ...
'Value', true,...
'FontName', scheme.Checkbox.Font.Value,...
'FontColor',scheme.Checkbox.FontColor.Value, ...
'FontSize', scheme.Checkbox.FontSize.Value,...
'Tooltip','If selected bad channels will be removed.  If not they will be marked as bad, but not removed.');
cBottom = cBottom - cDist;
handles.check_flatline = uicheckbox('Parent', handles.panel(2),...
'Position', [10, cBottom, 400, 20],...
'Text', 'Apply flatline channel criteria', ...
'Value', true,...
'FontName', scheme.Checkbox.Font.Value,...
'FontColor',scheme.Checkbox.FontColor.Value, ...
'FontSize', scheme.Checkbox.FontSize.Value,...
'Tooltip','Will remove or mark bad channels if they flatline for longer then the desired time interval.');
cBottom = cBottom - cDist;
handles.check_lineCriteria = uicheckbox('Parent', handles.panel(2),...
'Position', [10, cBottom, 400, 20],...
'Text', 'Remove/Mark channels with line noise amplitude that exceeds:', ...
'Value', true,...
'FontName', scheme.Checkbox.Font.Value,...
'FontColor',scheme.Checkbox.FontColor.Value, ...
'FontSize', scheme.Checkbox.FontSize.Value,...
'Tooltip','Will remove or mark bad channels that exceed the baseline level of line noise.');
handles.edit_lineCriteria = uieditfield(handles.panel(2), 'numeric',...
'AllowEmpty','off',...
'Value',4,...
'BackgroundColor',scheme.Edit.BackgroundColor.Value,...
'FontColor',scheme.Edit.FontColor.Value,...
'FontName', scheme.Edit.Font.Value,...
'FontSize', scheme.Edit.FontSize.Value,...
'ValueDisplayFormat', '%.1f SD',...
'RoundFractionalValues','off',...
'Limits',[0,inf],...
'Position', [380, cBottom, 80, 20]);
cBottom = cBottom - cDist;
handles.check_chanCriteria = uicheckbox('Parent', handles.panel(2),...
'Position', [10, cBottom, 400, 20],...
'Text', 'Remove/Mark channels with a neighborhood correlation less than:', ...
'Value', true,...
'FontName', scheme.Checkbox.Font.Value,...
'FontColor',scheme.Checkbox.FontColor.Value, ...
'FontSize', scheme.Checkbox.FontSize.Value,...
'Tooltip','Remove or mark bad channels that have a lower than the desired correlation with their neighbors.');
handles.edit_chanCriteria = uieditfield(handles.panel(2), 'numeric',...
'AllowEmpty','off',...
'Value',.8,...
'BackgroundColor',scheme.Edit.BackgroundColor.Value,...
'FontColor',scheme.Edit.FontColor.Value,...
'FontName', scheme.Edit.Font.Value,...
'FontSize', scheme.Edit.FontSize.Value,...
'ValueDisplayFormat', '%.2f',...
'RoundFractionalValues','off',...
'Limits',[0,1],...
'Position', [380, cBottom, 80, 20]);
cBottom = pheights(3) - 50;
handles.check_ASRCriteria = uicheckbox('Parent', handles.panel(3),...
'Position', [10, cBottom, 400, 20],...
'Text', 'ASR cleaning of segments with noise level greater than:', ...
'Value', true,...
'FontName', scheme.Checkbox.Font.Value,...
'FontColor',scheme.Checkbox.FontColor.Value, ...
'FontSize', scheme.Checkbox.FontSize.Value,...
'Tooltip','Attempt to correct any sections of data whose variance exceeds baseline by the designated amount (SD). Smaller values (e.g. 5) provide more aggresive cleaning and larger values (.e.g 20) more relaxed cleaning.');
handles.edit_ASRCriteria = uieditfield(handles.panel(3), 'numeric',...
'AllowEmpty','off',...
'Value',20,...
'BackgroundColor',scheme.Edit.BackgroundColor.Value,...
'FontColor',scheme.Edit.FontColor.Value,...
'FontName', scheme.Edit.Font.Value,...
'FontSize', scheme.Edit.FontSize.Value,...
'ValueDisplayFormat', '%.1f SD',...
'RoundFractionalValues','off',...
'Limits',[0,100],...
'Position', [380, cBottom, 80, 20]);
cBottom = cBottom - cDist;
handles.check_remBurstCriteria = uicheckbox('Parent', handles.panel(3),...
'Position', [10, cBottom, 400, 20],...
'Text', 'Remove unrepaired intervals of data', ...
'Value', true,...
'FontName', scheme.Checkbox.Font.Value,...
'FontColor',scheme.Checkbox.FontColor.Value, ...
'FontSize', scheme.Checkbox.FontSize.Value,...
'Tooltip','Remove interavls in which the desired portion of channels still have bad data after an attempted repair');
handles.edit_remBurstCriteria = uieditfield(handles.panel(3), 'numeric',...
'AllowEmpty','off',...
'Value',.25,...
'BackgroundColor',scheme.Edit.BackgroundColor.Value,...
'FontColor',scheme.Edit.FontColor.Value,...
'FontName', scheme.Edit.Font.Value,...
'FontSize', scheme.Edit.FontSize.Value,...
'ValueDisplayFormat', '%.2f',...
'RoundFractionalValues','off',...
'Limits',[0,1],...
'Position', [380, cBottom, 80, 20]);
handles.check_visChanges = uicheckbox('Parent', handles.figure,...
'Position', [20, 20, 400, 20],...
'Text', 'Visualize changes for each participant', ...
'Value', true,...
'FontName', scheme.Checkbox.Font.Value,...
'FontColor',scheme.Checkbox.FontColor.Value, ...
'FontSize', scheme.Checkbox.FontSize.Value,...
'Tooltip','If checked, a window will appear showing the before and after for every participant.');

handles.check_lineCriteria.UserData = handles.edit_lineCriteria;
handles.check_chanCriteria.UserData = handles.edit_chanCriteria;
handles.check_ASRCriteria.UserData = handles.edit_ASRCriteria;
handles.check_remBurstCriteria.UserData = handles.edit_remBurstCriteria;

handles.check_lineCriteria.ValueChangedFcn = {@callback_toggleState, handles};
handles.check_chanCriteria.ValueChangedFcn = {@callback_toggleState, handles};
handles.check_ASRCriteria.ValueChangedFcn = {@callback_toggleState, handles};
handles.check_remBurstCriteria.ValueChangedFcn = {@callback_toggleState, handles};

handles.button_clean.ButtonPushedFcn = {@callback_cleanData, handles, study, files};
