function h = study_TF_GUI(study, filenames)

p = plot_params;

scrsize = get(0, 'ScreenSize');
Wdth = 450; Hght = 300;
Bttn_HalfWidth = 12;
Bttn_HalfHeight = 18;
LBHeight = Hght * .95;

%setup the main figure window
handles.figure = uifigure;
h = handles.figure;

set(handles.figure,...
    'Color', p.backcolor, ...
    'Name', 'Time Frequency Calculation',...
    'NumberTitle', 'off',...
    'Position', [(scrsize(3)-Wdth)/2,(scrsize(4)-Hght)/2,Wdth,Hght],...
    'Resize', 'off',...
    'menubar', 'none',...
    'WindowStyle', 'modal');

%*************************************************************************
%start at the bottom with the buttons

handles.button_filter = uibutton(...
    'Parent', handles.figure,...
    'Text', 'Compute',...
    'Position', [Wdth-p.buttonwidth-10, 5, p.buttonwidth, p.buttonheight],...
    'BackgroundColor', p.buttoncolor,...
    'FontColor', p.buttonfontcolor);

handles.button_test = uibutton(...
    'Parent', handles.figure,...
    'Text', 'Test',...
    'Position', [Wdth-(p.buttonwidth*2)-20, 5, p.buttonwidth, p.buttonheight],...
    'BackgroundColor', p.buttoncolor,...
    'FontColor', p.buttonfontcolor);

handles.button_cancel = uibutton(...
    'Parent', handles.figure,...
    'Text', 'Cancel',...
    'Position', [Wdth-(p.buttonwidth*3)-30, 5, p.buttonwidth, p.buttonheight],...
    'BackgroundColor', p.buttoncolor,...
    'FontColor', p.buttonfontcolor,...
    'ButtonPushedFcn', {@callback_close});

handles.check_removemean = uicheckbox(handles.figure, ...
    'Text', 'Remove mean from single trials.',...
    'Value', 1,...
    'Position', [200, 50, 200, 20]);

handles.edit_baselinelow = uieditfield(handles.figure, ...
    'numeric',...
    'Value', 1.0,...
    'FontColor', p.textfieldfontcolor,...
    'BackgroundColor', p.textfieldbackcolor, ...
    'Position', [200, 90, 50, 25]);

handles.edit_baselinehigh = uieditfield(handles.figure, ...
    'numeric',...
    'Value', 0,...
    'FontColor', p.textfieldfontcolor,...
    'BackgroundColor', p.textfieldbackcolor, ...
    'Position', [260, 90, 50, 25]);

handles.check_prestim = uicheckbox(handles.figure, ...
    'Value', true, ...,...
    'Text', 'Use prestim',...
    'Position', [320, 90, 100, 25]);

uilabel('Parent', handles.figure, ...
    'Text', sprintf('Baseline range [min max]'),...
    'HorizontalAlignment', 'left', ...
    'BackGroundColor', p.backcolor, ...
    'Position', [20, 95, 150, 20]);

handles.edit_freqslow = uieditfield(handles.figure, ...
    'numeric',...
    'Value', 1,...
    'FontColor', p.textfieldfontcolor,...
    'BackgroundColor', p.textfieldbackcolor, ...
    'Position', [200, 130, 50, 25]);

handles.edit_freqshigh = uieditfield(handles.figure, ...
    'numeric',...
    'Value', 50,...
    'FontColor', p.textfieldfontcolor,...
    'BackgroundColor', p.textfieldbackcolor, ...
    'Position', [260, 130, 50, 25]);

handles.check_prestim = uicheckbox(handles.figure, ...
    'Value', true, ...,...
    'Text', 'Use defaults',...
    'Position', [320, 130, 100, 25]);

uilabel('Parent', handles.figure, ...
    'Text', sprintf('Frequency range (Hz) [min max]'),...
    'HorizontalAlignment', 'left', ...
    'BackGroundColor', p.backcolor, ...
    'Position', [20, 130, 180, 20]);

handles.edit_winsize = uieditfield(handles.figure, ...
    'numeric',...
    'Value', 256,...
    'FontColor', p.textfieldfontcolor,...
    'BackgroundColor', p.textfieldbackcolor, ...
    'Position', [200, 165, 110, 25],...
    'HorizontalAlignment','center');

handles.check_winsize = uicheckbox(handles.figure, ...
    'Value', true, ...,...
    'Text', 'Use defaults',...
    'Position', [320, 165, 100, 25]);

uilabel('Parent', handles.figure, ...
    'Text', sprintf('Window size (samples)'),...
    'HorizontalAlignment', 'left', ...
    'BackGroundColor', p.backcolor, ...
    'Position', [20, 165, 180, 20]);


%*********************************

handles.edit_cycles = uieditfield(handles.figure, ...
    'numeric',...
    'Value', 3,...
    'FontColor', p.textfieldfontcolor,...
    'BackgroundColor', p.textfieldbackcolor, ...
    'Position', [200, 200, 50, 25]);

handles.edit_cycleschange = uieditfield(handles.figure, ...
    'numeric',...
    'Value', 0.8,...
    'FontColor', p.textfieldfontcolor,...
    'BackgroundColor', p.textfieldbackcolor, ...
    'Position', [260, 200, 50, 25]);

handles.check_usefft = uicheckbox(handles.figure, ...
    'Value', true, ...,...
    'Text', 'Use FFT',...
    'Position', [320, 200, 100, 25]);

uilabel('Parent', handles.figure, ...
    'Text', sprintf('Wavelet Cycles [start, fact/end]'),...
    'HorizontalAlignment', 'left', ...
    'BackGroundColor', p.backcolor, ...
    'Position', [20, 200, 180, 20]);


handles.edit_cycleschange = uieditfield(handles.figure, ...
    'numeric',...
    'Value', 32,...
    'FontColor', p.textfieldfontcolor,...
    'BackgroundColor', p.textfieldbackcolor, ...
    'Position', [200, 235, 110, 25]);


uilabel('Parent', handles.figure, ...
    'Text', sprintf('Channel for testing'),...
    'HorizontalAlignment', 'left', ...
    'BackGroundColor', p.backcolor, ...
    'Position', [20, 235, 180, 20]);



handles.button_filter.ButtonPushedFcn = {@callback_filter, handles, filenames, study};


%**************************************************************************
function callback_close(hObject, eventdata)
closereq();


%**********************************************
function callback_filter(hObject, eventdata, h, filenames, study)


    file_id = '_filt';
    start = clock;

    if  h.radio_lowpass.Value == 1
        ledge = 0;
    else
        ledge = h.edit_lowfilt.Value;
    end
    
    if h.radio_highpass.Value == 1
        hedge = 0;
    else
        hedge = h.edit_highfilt.Value;
    end
    
    
    if (ledge > 0) && (hedge > 0) 
        if ledge >= hedge
        msgbox('Low edge cannot exceed high edge range')
        return
        end
    end


    revfilt = h.radio_notch.Value;
    owrite = h.check_overwrite.Value;
    
    try    
    %set a progress bar
    pbar = uiprogressdlg(h.figure,...
        'Title', 'filtering in progress',...
        'ShowPercentage', 'on');
   
    option = 0;
    nfile = length(filenames);
       
        for jj = 1:nfile
            [path, file, ext] = fileparts(filenames{jj});
            if owrite
                outfilename = file;
            else
                [file_id, option,writeflag] = wwu_verifySaveFile(path, file, file_id, ext, option);
                if option == 3 && ~writeflag
                    fprintf('skipping existing file...\n')
                    continue;
                else
                    outfilename = [file, file_id];
                end
            end
            
            EEGIn = wwu_LoadEEGFile(filenames{jj});
            fprintf('Filtering the data\n');
            
            fprintf('lowcutoff %f, highcutoff %f, revfilt %f\n', ledge, hedge, revfilt)
            EEGIn = pop_eegfiltnew( EEGIn, 'locutoff', ledge, 'hicutoff', hedge, 'revfilt', revfilt);
            newfile = fullfile(path, [outfilename, ext]);
            wwu_SaveEEGFile(EEGIn, newfile);
        
            pbar.Value  = jj/nfile;
    
        end
        
        clear EEGIn
        close(pbar)
    
        params = filenames;
        params(end+1) = {'locutoff'};
        params(end+1) = {ledge};
        params(end+1) = {'highcutoff'};
        params(end+1) = {hedge};
        study = study_AddHistory(study, 'start', start, 'finish', clock,'event', 'Filter', 'function', 'study_Filter_GUI', 'paramstring', params, 'fileID', file_id);
        study = study_SaveStudy(study);
    
    
        closereq();
    catch ME
        close(pbar);
        closereq();
        rethrow(ME)
    end

