function study_ExtractEpochs_GUI

p = plot_params;

W = 450; H = 150;
figpos = [(p.screenwidth-W)/2,(p.screenheight-H)/2, W, H];
%setup the main figure window

handles.figure = uifigure(...
    'Color', p.backcolor,...
    'Position', figpos,...
    'NumberTitle', p.numbertitle,...
    'Menubar', p.menubar,...
    'Name', 'Extract trials');

h = handles.figure;

handles.uipanel1 = uipanel(handles.figure,...
    'Position', [10,40, W-20, H-50]);

handles.button_extact = uibutton(...
    'Parent', handles.figure,...
    'Position', [W-90,5, 80, 25],...
    'BackgroundColor', p.buttoncolor,...
    'FontColor', p.buttonfontcolor,...
    'Text', 'Extract');
    
handles.button_extact = uibutton(...
    'Parent', handles.figure,...
    'Position', [W-190,5, 80, 25],...
    'BackgroundColor', p.buttoncolor,...
    'FontColor', p.buttonfontcolor,...
    'Text', 'Cancel');

handles.check_badtrials = uicheckbox(...
    'Parent', handles.uipanel1,...
    'Value' , 1, ...
    'position', [30,60, 200, 25],...
    'Text', 'Exclude bad trials');

handles.check_badtrials = uicheckbox(...
    'Parent', handles.uipanel1,...
    'Value' , 1, ...
    'position', [30,20, 200, 25],...
    'Text', 'Exclude bad components');



    




