function study_ExtractEpochs_GUI

p = plot_params;
scheme = eeg_LoadScheme;

W = 450; H = 150;
figpos = [(scheme.ScreenWidth-W)/2,(scheme.ScreenHeight-H)/2, W, H];
%setup the main figure window

handles.figure = uifigure(...
    'Position', figpos,...
    'NumberTitle', 'off',...
    'Menubar', 'none',...
    'Name', 'Extract trials',...
    'Color', scheme.Window.BackgroundColor.Value);
h = handles.figure;

handles.uipanel1 = uipanel(handles.figure,...
    'Position', [10,40, W-20, H-50,...
    'ForegroundColor', scheme.Panel.FontColor.Value]);

handles.button_extact = uibutton(...
    'Parent', handles.figure,...
    'Position', [W-90,5, 80, 25],...
    'BackgroundColor', scheme.Button.BackgroundColor.Value,...
    'FontColor',scheme.Button.FontColor.Value,...
    'FontSize', scheme.Button.FontSize.Value,...
    'FontName', scheme.Button.FontName.Value,...
    'Text', 'Extract');
    
handles.button_extact = uibutton(...
    'Parent', handles.figure,...
    'Position', [W-190,5, 80, 25],...
    'BackgroundColor', p.buttoncolor,...
    'FontColor', p.buttonfontcolor,...
    'Text', 'Cancel');

handles.check_badtrials = uicheckbox(...
    'Parent', handles.uipanel1,...
    'Value' , 1, ...
    'position', [30,60, 200, 25],...
    'Text', 'Exclude bad trials');

handles.check_badtrials = uicheckbox(...
    'Parent', handles.uipanel1,...
    'Value' , 1, ...
    'position', [30,20, 200, 25],...
    'Text', 'Exclude bad components');



    




